name: pump
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  video_player: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.11.0"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/chest/
    - assets/bicep/
    - assets/tricep/
    - assets/shoulder/
    - assets/back/
    - assets/legs/
    - assets/abs/
    - assets/gifpath/

    

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logopump.png"




